---
sidebar: sidebar 
permalink: install-setup/power-on-hardware.html 
keywords: aide, ai, data engine, ai data engine dcn, data compute node, afx, afx 1k, power on, 
summary: 각 쉘프의 전원을 켜서 고유한 쉘프 ID를 할당하고, AFX 컨트롤러 노드의 전원을 켠 다음, 전원 케이블을 고정하십시오. 
---
= AI Data Engine용 데이터 컴퓨팅 노드 전원 켜기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
랙 하드웨어를 설치하고 데이터 컴퓨팅 노드에 케이블을 연결한 후에는 DCN 및 AFX 스토리지 시스템의 컨트롤러 노드가 아직 켜져 있지 않은 경우 전원을 켜야 합니다.

.시작하기 전에
* 선반에 전원이 공급되고 각 선반에 고유한 선반 ID가 할당되었는지 확인하십시오. AFX 스토리지 시스템의 선반 ID 할당에 대한 자세한 내용은 link:https://docs.netapp.com/us-en/ontap-afx/install-setup/power-on-hardware.html#step-1-power-on-the-shelf-and-assign-shelf-id["고유한 쉘프 ID 할당"^]을(를) 참조하십시오.


.단계
스토리지 셸프를 켜고 고유 ID를 할당한 후 DCN의 전원을 켜고 스토리지 컨트롤러 노드가 아직 켜져 있지 않은 경우 전원을 켜십시오.

. 노트북을 시리얼 콘솔 포트에 연결하세요. 이렇게 하면 컨트롤러 전원이 켜질 때 부팅 과정을 모니터링할 수 있습니다.
+
.. 노트북의 시리얼 콘솔 포트를 115,200보드, N-8-1로 설정합니다.
+
시리얼 콘솔 포트 구성 방법에 대한 지침은 노트북의 온라인 도움말을 참조하십시오.

.. 콘솔 케이블을 노트북에 연결하고 스토리지 시스템과 함께 제공된 콘솔 케이블을 사용하여 컨트롤러의 직렬 콘솔 포트에 연결합니다.
.. 노트북을 관리 서브넷의 스위치에 연결하십시오.
+
image::../media/drw_afx_1k_console_connection_ieops-2708.svg[콘솔 연결]





. 관리 서브넷에 있는 TCP/IP 주소를 랩톱에 할당하십시오.
. 컨트롤러 전원 공급 장치에 전원 코드를 꽂은 다음 다른 회로의 전원에 연결하십시오.
+
image::../media/drw_affa1k_power_source_icon_ieops-1700.svg[전원 연결 다이어그램]

+
** 시스템 부팅이 시작됩니다. 초기 부팅에는 최대 8분이 소요될 수 있습니다.
** LED가 깜박이고 팬이 작동하기 시작하면 컨트롤러에 전원이 공급되고 있음을 나타냅니다.
** 팬이 처음 작동할 때 소음이 발생할 수 있는데, 이는 정상입니다.




. 데이터 컴퓨팅 노드 전원 공급 장치에 전원 코드를 꽂은 다음 서로 다른 회로의 전원에 연결합니다.
. 각 전원 공급 장치의 고정 장치를 사용하여 전원 코드를 고정합니다.
. 데이터 컴퓨팅 노드의 전원을 켭니다.
+
전원 스위치에 접근하려면 베젤을 제거해야 할 수도 있습니다. 만약 제거해야 했다면, 나중에 다시 설치해야 한다는 것을 잊지 마세요.



.다음 단계
데이터 컴퓨팅 노드를 켠 후 link:../install-setup/cluster-setup-afx.html["ONTAP AIDE 클러스터를 설정하세요"].
