---
sidebar: sidebar 
permalink: install-setup/prepare-hardware.html 
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, prepare, hardware installation, afx, afx 1k, 
summary: ONTAP 환경에 AI Data Engine용 데이터 컴퓨팅 노드를 설치하고 하드웨어를 등록하여 지원 혜택을 받을 준비를 하십시오. 
---
= AI Data Engine용 데이터 컴퓨팅 노드 설치 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI Data Engine(AIDE)용 데이터 컴퓨팅 노드를 설치하려면 설치 장소를 준비하고, 박스를 개봉하여 내용물을 포장 명세서와 대조하고, 시스템을 등록하여 지원 혜택을 받으세요.



== 1단계: 사이트 준비

데이터 컴퓨팅 노드를 설치하려면 사용하려는 사이트와 캐비닛 또는 랙이 구성 사양을 충족하는지 확인하십시오.

.단계
.  https://hwu.netapp.com["NetApp Hardware Universe"^]를 사용하여 사이트가 데이터 컴퓨팅 노드에 필요한 환경 및 전기적 요구 사항을 충족하는지 확인하십시오.
. 기존 AFX 1K 스토리지 시스템 설치 내에 데이터 컴퓨팅 노드를 위한 충분한 캐비닛 공간이 있는지 확인하십시오.
+
** 각 데이터 컴퓨팅 노드당 1U
** 각 AFX 1K 컨트롤러 노드당 2U
** 각 NX224 쉘프당 2U
** 스위치 모델에 따라 스위치당 1U 또는 2U입니다.






== 2단계: 상자 개봉

데이터 컴퓨팅 노드에 사용할 사이트와 캐비닛 또는 랙이 필요한 사양을 충족하는지 확인한 후 모든 상자를 개봉하고 내용물을 포장 명세서에 기재된 품목과 비교하십시오.

.단계
. 모든 상자를 조심스럽게 열고 내용물을 정리된 상태로 꺼내 놓으세요.
. 개봉한 물품을 포장 명세서와 대조하여 차이점이 있으면 기록해 두십시오.
+
배송 상자 측면에 있는 QR 코드를 스캔하면 포장 목록을 확인할 수 있습니다.

+
다음 항목은 상자에서 볼 수 있는 내용물의 일부입니다.

+
[cols="12,9,4"]
|===


| *하드웨어* | *케이블* |  


 a| 
** 베젤
** 지침이 포함된 레일 키트
** 데이터 컴퓨팅 노드

 a| 
** 전원 코드

|  
|===




== 3단계: 데이터 컴퓨팅 노드 등록

사이트가 데이터 컴퓨팅 노드 사양 요구 사항을 충족하는지 확인하고 주문한 모든 부품을 받았는지 확인한 후 시스템을 등록해야 합니다.

.단계
. 데이터 컴퓨팅 노드의 일련 번호를 찾습니다.
+
일련 번호는 다음 위치에서 찾을 수 있습니다.

+
** 포장 명세서에
** 확인 이메일에
** 각 데이터 컴퓨팅 노드 또는 일부 시스템에서는 각 데이터 컴퓨팅 노드의 시스템 관리 모듈에서.
+
image::../media/drw_ssn_label.svg[시스템 일련 번호의 예]



.  http://mysupport.netapp.com/["NetApp 지원 사이트"^]로 이동합니다.
. 스토리지 시스템을 등록해야 하는지 확인합니다.
+
[cols="1a,2a"]
|===
| 다음과 같은 경우: | 다음 단계를 따르십시오. 


 a| 
기존 NetApp 고객
 a| 
.. 사용자 이름과 비밀번호로 Sign in하세요.
.. *Systems* > *My Systems*를 선택합니다.
.. 새 일련 번호가 나열되어 있는지 확인합니다.
.. 일련 번호가 목록에 없는 경우 새로운 NetApp 고객을 위한 지침을 따르십시오.




 a| 
새로운 NetApp 고객
 a| 
.. 계정을 만들려면 *Register Now*를 클릭하십시오.
.. *Systems* > *Register Systems*를 선택합니다.
.. 스토리지 시스템의 일련 번호와 요청된 세부 정보를 입력하십시오.


NetApp에서 등록을 승인하면 필요한 소프트웨어를 다운로드할 수 있습니다. 승인에는 최대 24시간이 소요됩니다.

|===


.다음 단계
데이터 컴퓨팅 노드를 설치할 준비가 완료되면 link:deploy-hardware.html["Data Compute Node를 설치합니다"].
