---
sidebar: sidebar 
permalink: workspaces/prepare-data-for-aide.html 
keywords: aide, workspaces, create data container, ai data engine 
summary: 클러스터를 생성한 후에는 AI Data Engine에서 사용할 데이터가 포함된 데이터 컨테이너를 생성할 수 있습니다. 
---
= AI Data Engine용 데이터 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 생성한 후 AI Data Engine(AIDE)에서 사용할 데이터를 담을 데이터 컨테이너를 설정하십시오. 이 데이터 컨테이너는 ONTAP 볼륨이어야 하며, 로컬 볼륨이거나 ONTAP 9를 실행하는 피어링된 ONTAP 클러스터의 볼륨이어야 합니다.

ONTAP 클러스터 데이터를 AIDE에 수동으로 업로드하는 대신 대상 클러스터와 SVM을 AIDE 클러스터와 피어링한 다음 AIDE 메타데이터 카탈로그에서 사용할 NFS 볼륨을 결정해야 합니다. 데이터 컨테이너를 생성한 후 워크스페이스를 생성하고 해당 워크스페이스와 데이터 컨테이너를 연결할 수 있습니다. 그러면 해당 워크스페이스 사용자는 AI 워크로드에 필요한 워크스페이스 관련 데이터 수집 및 리소스에 액세스하고 상호 작용할 수 있습니다.

.이 작업 정보
AI Data Engine에서 사용하려는 데이터가 포함된 각 SVM을 피어링해야 합니다. 클러스터만 피어링하는 것으로는 충분하지 않습니다. 이렇게 해야 AI Data Engine이 의도한 대로 데이터에 액세스하고, 온보딩하고, 인덱싱할 수 있습니다.

SnapMirror 타겟 역할을 할 AIDE 클러스터의 SVM을 피어링해야 합니다.

ONTAP 클러스터와 AIDE 클러스터 간에 SnapMirror 관계를 생성할 필요가 없습니다. 이러한 관계는 워크스페이스 생성 시 자동으로 생성됩니다.

.시작하기 전에
* 클러스터와 SVM을 피어링하고 데이터 컨테이너를 선택하려면 스토리지 관리자 권한이 필요합니다.
* AI Data Engine에서 사용할 데이터가 포함된 ONTAP 클러스터 및 SVM을 식별했습니다.
* 데이터 소스 볼륨이 다음 요구 사항을 충족했음을 확인했습니다.
+
** 볼륨이 온라인 상태이며 액세스할 수 있습니다.
** NFS 프로토콜이 활성화되어 있습니다. NFS가 활성화된 볼륨만 AI Data Engine의 데이터 컨테이너로 지원됩니다. SMB 및 CIFS 볼륨은 지원되지 않습니다.
** 해당 볼륨은 FlexCache 볼륨이 아닙니다.
** 데이터 소스는 읽기/쓰기 가능한 볼륨입니다. 데이터 보호 볼륨은 지원되지 않습니다.




.단계
. https://docs.netapp.com/us-en/ontap-afx/protect-data/create-peer-relationship.html["각 ONTAP 클러스터와 SVM을 피어링합니다"^] AI Data Engine에서 사용할 데이터가 포함되어 있습니다.
. link:../install-setup/cluster-setup-afx.html["AI Data Engine에서 사용할 볼륨을 선택합니다"].
+
각 볼륨에 대해 다음 정보를 기록해 두십시오.

+
** 볼륨 이름
** UUID
** SVM 이름 및 UUID
** 클러스터 이름 및 UUID




.다음 단계
link:create-workspace.html["워크스페이스 만들기"] 생성한 데이터 컨테이너를 워크스페이스와 연결합니다.

.관련 정보
* https://docs.netapp.com/us-en/ontap-afx/manage-data/prepare-manage-data.html#data-migration-options["데이터 마이그레이션 옵션"^]

