---
sidebar: sidebar 
permalink: administer/aide-node-replace.html 
keywords: ai data engine, aide, data compute node, dcn, replace node, node replacement, cluster maintenance 
summary: '하드웨어 장애, 업그레이드 또는 유지 보수로 인해 데이터 컴퓨팅 노드가 작동을 멈추거나 교체가 필요한 경우 AI Data Engine(AIDE) 클러스터에서 해당 노드를 교체해야 합니다.' 
---
= AI Data Engine 클러스터의 노드를 교체하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI Data Engine(AIDE) 클러스터에서 데이터 컴퓨팅 노드가 작동을 멈추거나 하드웨어 장애, 업그레이드 또는 유지 보수로 인해 교체해야 하는 경우 해당 노드를 교체해야 합니다. 이렇게 하면 AIDE 클러스터가 정상적으로 작동하도록 유지할 수 있습니다. 이 절차는 진행 중인 서비스를 중단하지 않고 수행할 수 있습니다.



== 노드 교체 준비

AIDE 클러스터에서 노드를 교체하기 전에 고려해야 할 사항이 몇 가지 있습니다.



=== 요구 사항

다음이 필요합니다.

* _storage administrator_ 권한이 있는 사용자 자격 증명
* 새 교체 노드의 일련 번호




=== 제한 사항

AIDE 클러스터에서 노드를 교체할 때 다음 제한 사항에 유의해야 합니다.

* 노드 교체는 CLI를 통해서만 지원되며 선택적으로 REST API를 사용할 수 있습니다.
* System Manager를 사용하여 노드 교체를 수행할 수 없습니다.
* 새 노드는 클러스터의 소프트웨어 버전과 일치해야 합니다. 필요한 경우 ONTAP에서 업데이트합니다.
* IP 주소 충돌을 방지하려면 장애가 발생한 노드를 클러스터 네트워크에 연결한 상태에서 전원을 켜지 않아야 합니다.




== AIDE 클러스터에서 데이터 컴퓨팅 노드 교체

다음 절차에 따라 AIDE 클러스터의 데이터 컴퓨팅 노드를 교체할 수 있습니다.

.단계
. 장애가 발생한 노드를 물리적으로 제거합니다
+
노드의 전원을 끄고 클러스터 네트워크에서 연결을 해제하십시오. 교체 과정 동안 노드가 네트워크에 연결된 상태로 부팅되지 않도록 하십시오.

. 다음 명령을 사용하여 클러스터에서 장애가 발생한 노드를 삭제합니다.
+
`dcn cluster node delete -name <node_name> -force true`

+
<node_name> 값의 실제 이름을 입력합니다.

. 새 노드를 클러스터에 물리적으로 연결합니다
+
노드가 케이블로 연결되어 있고 전원이 켜져 있으며 검색 가능한 상태인지 확인하십시오.

. 검색 가능한 노드와 구성되지 않은 노드를 확인하여 새 노드가 온라인 상태인지 확인합니다.
+
`dcn cluster node show -membership available`

. 다음 명령을 사용하여 노드를 클러스터에 추가합니다.
+
`dcn cluster node create -serial-number <new_node_serial>`

+
ONTAP는 새 노드에 IP 주소를 할당합니다. 노드의 소프트웨어 버전이 클러스터와 일치하지 않으면 ONTAP는 자동으로 노드를 업데이트합니다.

. 다음 명령 중 하나를 사용하여 클러스터 상태 및 노드 통합을 확인합니다.
+
`dcn cluster node show`

+
`dcn cluster node show -instance`



.관련 정보
* link:../administer/dcn-add-node.html["컴퓨팅 클러스터 확장"]

