---
sidebar: sidebar 
permalink: policies/manage-policies.html 
keywords: manage policies, edit policy, enable policy, disable policy, delete policy 
summary: 저장된 정책을 검토하여 현재 각 기준에 맞는 파일을 확인하고 더 이상 필요하지 않은 정책을 제거하십시오. 
---
= AI Data Engine에서 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
저장된 정책 중 어떤 정책이 데이터와 일치하는지 검토하거나, 영향을 받는 파일 수를 비교하여 조치 우선순위를 정하거나, 더 이상 필요하지 않은 정책을 제거하려면 정책 페이지를 사용하십시오. 예를 들어, 여러 개의 콜드 데이터 정책을 가진 스토리지 관리자는 영향을 받는 파일 수를 비교하여 어떤 데이터 그룹에 먼저 조치를 취해야 하는지 결정할 수 있습니다.

각 정책 목록에는 현재 해당 기준과 일치하는 파일 및 개체의 수가 표시됩니다. 이 수를 사용하여 검토할 가치가 있는 데이터를 활발하게 수집하는 정책을 식별할 수 있습니다.



[[check-which-files-match-a-policy]]
== 정책과 일치하는 파일 확인

정책을 수정하거나 삭제하기 전에 현재 해당 정책과 일치하는 파일을 검토하여 기준이 여전히 올바른 데이터를 캡처하는지 확인하십시오.

.단계
. AI Data Engine UI에서 *정책*을 선택합니다.
. 정책 옆에 있는 작업 메뉴를 열고 *결과 조사*를 선택합니다.




[[edit-a-policy]]
== 정책 편집

.시작하기 전에
* _AI Data Engine 관리자_ 역할이 있어야 합니다.


.단계
. AI Data Engine UI에서 *정책*을 선택합니다.
. 수정하려는 정책의 작업 메뉴를 열고 *정책 편집*을 선택합니다.
. 필요에 따라 정책 이름, 설명 또는 조치를 업데이트하십시오.
. *저장*을 선택합니다.




[[delete-a-policy]]
== 정책 삭제

.시작하기 전에
* _AI Data Engine 관리자_ 역할이 있어야 합니다.



CAUTION: 삭제는 영구적이며 되돌릴 수 없습니다.

.단계
. AI Data Engine UI에서 *정책*을 선택합니다.
. 삭제하려는 정책의 작업 메뉴를 열고 *정책 삭제*를 선택하십시오.
. 미리 보기 대화 상자에서 삭제를 확인합니다.




[[related-information]]
== 관련 정보

* link:create-policy.html["정책 만들기"]
* link:../investigate/take-actions.html["데이터에 대한 조치를 취하십시오"]

